# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "install.packages('remotes'); remotes::install_github('ropenscilabs/tic'); tic::prepare_all_stages()"

cache:
- C:\RLibrary

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# Adapt as necessary starting from here

#on_failure:
#  - 7z a failure.zip *.Rcheck\*
#  - appveyor PushArtifact failure.zip

environment:
  GITHUB_PAT:
    secure: gP8Ckzs0mpkM+xdbkHo1kLtSIjQ/9MNxLbSMLJMxeILNhyLoVZG92HbjX1mBxA6d 
  id_rsa:
    secure: 0sqNZF1uXgOajRJTX4G3aU6VIgH/PVJ2IA4kqss5pqJuy23wmAhU7eaCR+zG0M7uZMxn4K78AlOsZa+ZgPlPoL2KlCIubwyuELUMoURNubnGAvUstI7uZQCZjgvl4QCwWUwSmdvH16SXGH4kEsnKH8ToUf3yuE12ab6k2D6emBuJdI0FZ1XxPztF4MtyjfUHqKGxaPcVx+Hgmu7MezaoDVbxkLn/IdZ9UQXypBAPqW4S6RjcjRh/QLkA1PJQRTEpIepSai506aWg1YScc4GvFZgtvtUVSVrHhAK74SAWBAFdQ0C2jr6EEqxurpTPjHY6buXX5OSaDB2ScdscHP6CqcxtJQdRZJVYrXodyDjBlzw2471iaL0WBPLA9MoroGXZMwu3cJJg/3BmtjMy6RIXbp/Mg61KtiyKXOlbe4fxLmInFP+ANvbi35y0tdiWaX+8qO+NTqabQUgNGuPX4mpfxrWwA+tbeRAqp4ygHR3VZWB0AD++tHAa2V4bANA6bYZORT3uHJkX6zQTC3KQS+inlKxDBPoysndTn/KwqLEL+NZC3/O6BC8fJuuJyGcUpq8SA4g0Z0EM2FKs7nCbN1paCNOY986NKq8M3WbPtlNk2Xb8K5sC/mRKu4XRbkldiyaPuervPyh/taYMDBV7frMagJG5ZhKIuq2sfOLWaS5JneIvlXpeVD1e/abmDifHycdsVWyNuF8vpwy/zmF3bQ/8T72Wuvsubcs+Isgj9Q09EXc0Qj2OJOoWBzVIBioUuFZU8IbCjTCcrFo/ypZ68lL0hheKio6Ko72E9ZoojpaaEIo5PPEiEtXqJ1IIHm/8HbQxWT5CvqK4HrWugdxi56E+t2OYcl7d+1O0BmJh1+7H+hbKpOJcg8IG1Z0lszmEsHPRIKN2cHLskaMpIZDQzQ7FR3U3urFLT3hiufMaDh2gM0p65EtViuh5PYUYAnmC/2cj85gTO5/sOF6b70Z9cfYSdrC36hsA2Oz34zVQRR01pJKj5OntndwM6W9x7Vo4TMsYjPJNXVv8sRqXPMb7r+dbDP+W0CdjyoRp+ug3Z1bordAP2s3cVxLJsEBJfOz+1un3adH+CyUkO768ZWEwBInnrn+V05CkIU5U0sJkr0PqWBxPuNVXezbAVklf8uAebl1qgQwUDoSdNMYSWA0ENVjslZzmHRVmd/jyMWncBeXq5cezTHYSY6QA44UJJt7sM6u5L7CPwH9Fjts0jd9CliFKSWRYKyF6odtNIR4y96HQxtOSrQ/6GQajJMyJyJ8Bp1ss6XLo6t9NAzhoLdSaVx3UA9xRjOjeEPI0PJNhNKAES9hPHdP8TLhawa0SxKiTcQXKDnU7l67IuYacP7zcEWtYIN31GmHZ88SUKRNLmfDeMjV8MEhYb3Gw/KUUZcOHRxb2DOxeW5V3J78AkuDBn2UIpYMmLkcVBmMM3wRTGMOdbq0JnvPweSapLOVBmKvnUghIW7WMClkrxTu68nSJIzcHbXoagLP1qXw/Kp3fIuZkgG8/uEScZzqvHgiC/JgOGXmtVSvGKLyUPihvjdSWP4yJy8tyjopFX0vgOYzz9/SkJ7AfYwdOLHp3ZwkMARcC3blwdJCUL3PiJZLL4UiXeZrfnGX8jjbpOVB6XfmAqkSx3bAjU5mLslFffDcqvq9GdcJB83/ZfPiCqfe81gARkAHSU9djpI7zeDNAJq9Gb7WSoS9jlwo1YAj0+nLTXWvxtFdmGfl67vcoNWjToRA3TYcF3DhUyKiTl2HQqTviqV7pQUmOjSrUkueEaqXVbePfRWqCBtGBBlFT6Mq8ZmMeP9Xk520PAoaXYckcoqSwZGyS38a162/BRWkGBYwe5EAyV5b30PgGXj8IMQls5j0xR4gTY0hNLivQErgO7sr4KlaXVkW7o9roPxSqIKU0voynKyMREwAdclXizVK+JMvItSqA27aF/sVmrqdXAzWfqauQIJHr41xckaEOGj9mScrAvXOWetkvavIejxNkWjIK5bmc6CoxAcedUTPZPPQlBaHuzB9e8VHPWGg53KnmrCf0v9aELj3gMW9VsVc59HYIZu5Z3N/CYIEXfTZmnhP7U9JRvlAYX7Ot2ZHA3FnlpevtKmSJUjkG3A8zZIUadlc1u2KBc0G5mSpkACD5Aw0aTKgyuc8t7HgB1ecxnouLMzmyGNjY+xAyp4a/pBOxtNbzBiLrOpfrKW5UrRkMYfxZLiy4sVoCibI/Fp8vyJD5fIBOxQPKJmrVKvxHHN7YQDloFxG5swUidDxqIosOTYJ+/Q5rXi54tyFwYKiJqKMeoxFdRrpvnw2/2SXpJJDtl+hPi/2yhX4UIC3zbgDvURD/fE5gjWf4P5CguXUCqs8ddiMgD9SjiPDrdoFKivtqzOyylYIAJ5RpQLiICR3Z5F7yfSCdw2zFjQVejGNBo4CPbshsSB9ETXlDljzPcvTUBj77QxGSNU6CJkhSveNbVHAWqxSyEIUHNyOY5+TvqtPxGi5Q1x7SjhPWUBarS74yP4eiYG6p01gOXuxe2CEOOBVGS4YYBZN/gXtlXcPieoIEsGwp78KkVnAlZSI9q1vrdPFahatxmGRRcSirtccbZEJFkzYvJ7oQFA5QPO/+QFj/mBzRJanYyl6WxYrImkKuh0nGaqFKG2LMb8cNqYloN8BWZa8VchBZ6+tnYjscewtj70S4TtPGqfCx7yvIlixTwEzJNzyMx51TPn6L9S0ueDfm37zG1kcHhmxITBv798Eu/c6UpzF6eP84yjiTS4LlnVQ4AlOhoefChNH5ZaMrmmtctmawY2SF8NUZEaVkz4TFecv8QOUrJ/3RqAxpnK1WcWnwQ4Jqdl9/kGNsXDnJh/zM4VtQUORzHn2sdO9oNLPwg05+5WUYy99CA9YIb9EkKd+z+jnOpR56m+l+8CxV1KAh386KZbqCmbVls81mOsxMyxUXcUOQucsasROrw14R+WkzrFiXuPft0vJax2YbEd5Di55ycEG8wpegnwGsfspB+Z1WNKEDZthxhcP7lz7IkEntU90MAPBX1ohQtx7YodFC7l9awtI=
     

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
